version: '3'

services:
  http-service:
    container_name: lostinspacebar-node
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    working_dir: /app
    ports:
      - 8080:8080
    networks:
      - lis-net
networks:
  lis-net: